### ISSUE TITLE
Error in data.frame

### ISSUE THREAD

**Issue by kellnerj** [adletaw/craigr#14]
Running the code in the help file:

rentals(location = "seattle", area = "see", bedrooms = 5, query = "downtown")

results in the following error message:

Error in data.frame(Title = titles, Date = dates, Price = prices, Bedrooms = beds,  : 
  arguments imply differing number of rows: 0, 2

**Comment by adletaw** [comment]
Thanks for finding.  I'm updating this now - looks like Craigslist changed their CSS classes some so its no longer finding the listings.
